home/urls.py
from django.urls import path
from .views import (
    about,
    landingpage,
    tags,
    new_question,
    thumbs,
    display_question_page,
    DeleteQuestionView,
    QuestionsListView,
)

urlpatterns = [
    path("about/", about, name="about"),
    path("", landingpage, name="landing-page"),
    path("tags/", tags, name="tags"),
    path("explore/", QuestionsListView.as_view(), name="explore-page"),
    path("explore/new_question", new_question, name="new-question"),
    path(
        "explore/question_<int:question_pk>/thumb/<string>/<int:answer_pk>",
        thumbs,
    ),
    path(
        "explore/question_<int:pk>/",
        display_question_page,
        name="question-detail",
    ),
    path(
        "explore/question_<int:pk>/delete",
        DeleteQuestionView.as_view(),
        name="question-delete",
    ),
]

shlifim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("users/", include("users.urls")),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.http import Http404
from .RichTextBleachField import RichTextBleachField
from django.db.models import Count
from users.models import Profile


class Subject(models.Model):
    subject_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.subject_name


class Sub_Subject(models.Model):
    sub_subject_name = models.CharField(max_length=100)
    related_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.sub_subject_name

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["sub_subject_name", "related_subject"],
                name="unique_sub_subject",
            )
        ]


class Book(models.Model):
    book_name = models.CharField(max_length=100, unique=True)
    related_subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.book_name


class Grade(models.TextChoices):
    GRADE7 = "7", "Seventh Grade"
    GRADE8 = "8", "Eighth grade"
    GRADE9 = "9", "Ninth grade"
    GRADE10 = "10", "Tenth grade"
    GRADE11 = "11", "Eleventh grade"
    GRADE12 = "12", "Twelfth grade"


class Question(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextBleachField(blank=True, null=True)
    publish_date = models.DateTimeField(default=timezone.now)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    sub_subject = models.ForeignKey(
        Sub_Subject, on_delete=models.CASCADE, blank=True, null=True
    )  # field not required
    grade = models.CharField(max_length=2, choices=Grade.choices)
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, null=True, blank=True
    )  # field not required
    book_page = models.IntegerField(
        null=True, blank=True, validators=[MinValueValidator(1), MaxValueValidator(999)]
    )  # field not required
    is_edited = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", through="Question_Tag")

    class Meta:
        ordering = ["-publish_date"]  # default ordered by publish_date

    def __str__(self):
        return f"Question #{self.id} : {self.title} ( {self.publish_date.strftime('%d/%m/%Y %H:%M')} )"

    # Input: a set of strings represting tag names.
    def add_tags_to_question(self, tags):
        for tag_name in tags:
            # if tag exist in DB - fetch the tag. else, create a new tag.
            tag, created = Tag.objects.get_or_create(tag_name=tag_name)
            if created:
                tag.tag_name = tag_name
                tag.save()
            # add a new Question_Tag only if tag not in self.tags.
            if tag not in self.tags.all():
                new_pair = Question_Tag()
                new_pair.question = self
                new_pair.tag = tag
                new_pair.save()

    def get_answers_feed(self, filter_type=""):
        """
        Get all the answers in the DB for that question
        Also get filter type param for chosing between date / likes count filter
        """
        answers = self.answer_set
        if filter_type == "date" or filter_type == "":
            answers = answers.order_by("-publish_date")
        elif filter_type == "votes":
            answers = answers.annotate(q_count=Count("likes")).order_by("-q_count")
        else:
            raise Http404()
        return answers

    def get_question_title(self):
        return str(self.subject) + "-" + self.title

    def get_answers_num(self):
        return self.answer_set.count()

    @classmethod
    def get_all_user_questions(cls, profile):
        return cls.objects.all().filter(profile=profile)


class Answer(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = RichTextBleachField(default="")
    publish_date = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(
        Profile, blank=True, related_name="user_answer_likes"
    )
    dislikes = models.ManyToManyField(
        Profile, blank=True, related_name="user_answer_dislikes"
    )
    is_edited = models.BooleanField(default=False)
    ordering = ["publish_date"]

    def __str__(self):
        return self.content

    def profile_liked(self, profile):
        return profile in self.likes.all()

    def profile_disliked(self, profile):
        return profile in self.dislikes.all()

    def set_is_edited(self, newVal):
        self.is_edited = newVal

    def handle_thumb_up(self, profile):
        liked = self.likes.filter(user_id=profile.user_id).exists()
        disliked = self.dislikes.filter(user_id=profile.user_id).exists()
        if liked:
            self.likes.remove(profile)
        else:
            self.likes.add(profile)
        if disliked:
            self.dislikes.remove(profile)

    def handle_thumb_down(self, profile):
        liked = self.likes.filter(user_id=profile.user_id).exists()
        disliked = self.dislikes.filter(user_id=profile.user_id).exists()

        if disliked:
            self.dislikes.remove(profile)
        else:
            self.dislikes.add(profile)
        if liked:
            self.likes.remove(profile)

    @classmethod
    def get_answers_tuples(cls, question, sort_answer_by, profile):
        answers = question.get_answers_feed(sort_answer_by)
        for answer in answers:
            answers_tuples = (
                    answer,
                    answer.profile_liked(profile),
                    answer.profile_disliked(profile),
            )
            yield answers_tuples

    @property
    def show_content(self):
        from django.utils.html import strip_tags

        return strip_tags(self.content)

    @classmethod
    def get_answers_by_date(cls):
        return cls.objects.order_by("-publish_date")

    @classmethod
    def get_all_user_answers(cls, profile):
        return cls.objects.all().filter(profile=profile)


class Tag(models.Model):
    tag_name = models.CharField(max_length=20)
    questions = models.ManyToManyField("Question", through="Question_Tag")

    def __str__(self):
        return self.tag_name

    # The function returnss all tags ordered by name tag.
    @classmethod
    def tags_feed(cls, search=""):
        return cls.objects.filter(tag_name__contains=search).order_by("tag_name")

    @classmethod
    def check_tag_array(cls, tags_array):
        is_valid = True
        if len(tags_array) > 5:
            is_valid = False
        for tag in tags_array:
            if len(tag) < 2 or len(tag) > 20 or not tag.isalnum():
                is_valid = False
        return is_valid


class Question_Tag(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="question_ID"
    )
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name="tag_ID")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["question", "tag"], name="question_tag")
        ]

    def __str__(self):
        return f"{self.question}, Tag : {self.tag}"

home/forms.py
from django import forms
from .models import Question, Answer
from .RichTextBleachField import RichTextBleachField


class QuestionForm(forms.ModelForm):
    tags_ = forms.CharField(max_length=110, min_length=0, required=False)

    class Meta:
        model = Question
        fields = (
            "title",
            "subject",
            "sub_subject",
            "grade",
            "book",
            "book_page",
            "tags_",
            "content",
        )

    def clean_sub_subject(self):
        subject = self.cleaned_data.get("subject")
        sub_subject = self.cleaned_data.get("sub_subject")
        if sub_subject and sub_subject not in subject.sub_subject_set.all():
            raise forms.ValidationError("The sub-subject doesn't match the subject")
        else:
            return sub_subject


class CommentForm(forms.ModelForm):
    content = RichTextBleachField(default="")

    class Meta:
        model = Answer
        fields = ("content",)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Question, Tag, Answer
from django.views.generic.list import ListView
from django.views.generic import DeleteView
from .forms import QuestionForm, CommentForm
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
import json


def about(request):
    return render(request, "home/about.html")


def landingpage(request):
    return render(request, "home/landingpage.html")


def display_question_page(request, pk):
    form = CommentForm(request.POST)
    question = get_object_or_404(Question, id=pk)
    sort_answer_by = request.GET.get("sortanswersby", "")
    context = {
        "question": question,
        "answers_tuples": Answer.get_answers_tuples(
            question, sort_answer_by, request.profile
        ),
        "answersCount": question.answer_set.count(),
        "tags": question.tags.values(),
        "title": question.get_question_title(),
        "is_user_logged_in": request.user.is_authenticated,
        "form": form,
    }
    if request.method == "POST":
        if form.is_valid():
            if request.profile is None:
                return HttpResponse("Unauthorized", status=401)
            else:
                form.instance.profile = request.profile
                form.instance.question = question
                form.save()
            return redirect(reverse("question-detail", kwargs={"pk": question.pk}))
    return render(request, "home/question_detail.html", context)


def thumbs(request, **kwargs):
    if request.user.is_authenticated:
        question_id = kwargs["question_pk"]
        answer = get_object_or_404(Answer, pk=kwargs["answer_pk"])
        if kwargs["string"] == "up":
            answer.handle_thumb_up(request.profile)
        elif kwargs["string"] == "down":
            answer.handle_thumb_down(request.profile)
        else:
            raise Http404
        return redirect("question-detail", question_id)
    else:
        return HttpResponse("Unauthorized", status=401)


def tags(request):
    if "q" in request.GET:
        search = request.GET["q"]
        tags = Tag.tags_feed(search)
    else:
        tags = Tag.tags_feed()
    return render(request, "home/tags.html", {"tags": tags})


@login_required(login_url="login")
def new_question(request):
    form = QuestionForm
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            tags_array = [
                t.strip().lower()
                for t in question_form.cleaned_data["tags_"].split(",")
            ]
            tags_status = Tag.check_tag_array(tags_array)
            if not question_form.data["tags_"] or tags_status:
                question_form = question_form.save(commit=False)
                question_form.profile = request.profile
                question_form.save()
                if tags_status:
                    question_instance = Question.objects.get(id=question_form.id)
                    question_instance.add_tags_to_question(tags_array)
                return redirect("question-detail", question_form.id)
            else:
                tags_error_msg = """Invalid data.
             You may enter up to 5 tags which are separated by ",".
             Each tag must have between 2-20 characters. And cannot contain special characters (like * # " etc.) """
                messages.error(
                    request, {"title": "ERROR:", "message_content": tags_error_msg}
                )
        else:
            validation_error = json.loads(question_form.errors.as_json())
            if question_form.has_error("sub_subject"):
                message_content = validation_error["sub_subject"][0]["message"]
            else:
                message_content = "Invalid data. Book number must be between 1-999."
            messages.error(
                request,
                {"title": "ERROR:", "message_content": message_content},
            )
    return render(
        request,
        "home/questions/new_question.html",
        {"form": form, "title": "New Question"},
    )


class QuestionsListView(ListView):
    model = Question
    template_name = "home/explore.html"
    ordering = ["-publish_date"]

    def get_context_data(self, **kwargs):
        requested_tag_name = self.request.GET.get("tag", None)

        if requested_tag_name:
            requested_tag_obj = get_object_or_404(Tag, tag_name=requested_tag_name)
            items_set = requested_tag_obj.question_set.all()
        else:
            items_set = Question.objects.all()

        context = {
            "tag": requested_tag_name,
            "questions": items_set,
        }

        context.update(kwargs)
        return super().get_context_data(**context)


class DeleteQuestionView(DeleteView):
    model = Question

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.profile == request.profile:
            messages.success(request, "SUCCESS: Your question has been deleted.")
            return super(DeleteQuestionView, self).delete(request, *args, **kwargs)
        else:
            return HttpResponse("Unauthorized", status=401)

    def get_success_url(self):
        return reverse_lazy("explore-page")

home/templates/home/about.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<html>
    <link rel="stylesheet" type="text/css" href="{% static 'home/CSS/about.css' %}">
    <body class="main-bg">
        <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                <br><br>
                <div class="about-us">
                    <h1><b>About Us</b></h1>
                    <br>
                    <p>Shlifim is a forum for helping students find answers to their homework and
                        assignments.</p>
                    <p>This web-based application project is part of a course by the Tel Aviv-Yafo Academic College 
                        under the guidance of RedHat programmers.</p>
                    <a href="https://github.com/beyond-io/shlifim">Visit our project on Github</a>
                </div>
                <br><br>
                <div class="contact-us">
                    <h1>Contact Us</h1>
                    <br>
                    <p>We are always growing!</p>
                    <p>If you have any suggestions for new Sub-Subjects or Books please contacts us via:</p>
                    <a href="mailto:shlifimcontact@gmail.com">shlifimcontact@gmail.com</a>
                    <br><br>
                    <div class="column">
                        <p>Aviv Zafrani</p>
                        <a href="https://github.com/avivz450">
                            <img src="{% static 'home/github.png' %}"
                            width="40" height="40"></a>
                        &ensp;
                        <a href="https://www.linkedin.com/in/aviv-zafrani-aa4351180/">
                            <img src="{% static 'home/linkedin.png' %}"
                            width="40" height="40"></a>
                        <br><br>
                    </div>
                    <div class="column">
                        <p>Danit Levi</p>
                        <a href="https://github.com/danitLevi">
                            <img src="{% static 'home/github.png' %}"
                            width="40" height="40"></a>
                        &ensp;
                        <a href="https://www.linkedin.com/in/danit-levi/">
                            <img src="{% static 'home/linkedin.png' %}"
                            width="40" height="40"></a>
                        <br><br>
                    </div>
                    <div class="column">
                        <p>Ido Kahlon</p>
                        <a href="https://github.com/idokk1">
                            <img src="{% static 'home/github.png' %}"
                            width="40" height="40"></a>
                        &ensp;
                        <a href="https://www.linkedin.com/in/ido-kahlon-61bbb01aa/">
                            <img src="{% static 'home/linkedin.png' %}"
                            width="40" height="40"></a>
                        <br><br>
                    </div>
                    <div class="column">
                        <p>Rebecca Tubman</p>
                        <a href="https://github.com/rebeccaTubman">
                            <img src="{% static 'home/github.png' %}"
                            width="40" height="40"></a>
                        &ensp;
                        <a href="https://www.linkedin.com/in/rebecca-tubman/">
                            <img src="{% static 'home/linkedin.png' %}"
                            width="40" height="40"></a>
                        <br><br>
                    </div>
                    <div class="column">
                        <p>Lior Noy</p>
                        <a href="https://github.com/liornoy">
                            <img src="{% static 'home/github.png' %}"
                            width="40" height="40"></a>
                        &ensp;
                        <a href="https://www.linkedin.com/in/lior-noy/">
                            <img src="{% static 'home/linkedin.png' %}"
                            width="40" height="40"></a>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>
</body>
{% endblock content %}

home/templates/home/answers_display.html
<article class="answers-container">
{% for answer, liked, disliked in answers_tuples %}
	<div class="answer-display mt-1 col-md-10",id="ans{{answer.id}}">
	<div class="row">
		<div class="asnwer-conent col-md-10">
			<p>{{ answer.content | safe }}</p>
			</div>
		<div class="answer-meta-data right pl-4 col-md-2 container">
		<div class="col-12">
			<b>by <a href="{% url 'user-page' answer.profile.pk  %}">{{ answer.profile }}<a> </b>
		</div>
		<div class="col-12">
			<small class="text-muted date">{{ answer.publish_date|date:"F d, Y" }}</small>
		</div>
		<div class="d-flex col-11 pt-3">
        <div class="pr-2">
			<a href="thumb/up/{{ answer.id }}"
			{% if not is_user_logged_in %} class="disabled"{% endif %}>
			{% if liked %} 
			<i class="bi bi-hand-thumbs-up-fill"></i>
			{% else %}
			<i class="bi bi-hand-thumbs-up"></i>
			{% endif %}
			</a >
			  {{ answer.likes.count }}
			<a href="thumb/down/{{ answer.id }}"
			  {% if not is_user_logged_in %}class="disabled"{% endif %}>
			  {% if disliked %}
				<i class="bi bi-hand-thumbs-down-fill"></i>
				{% else %}
				<i class="bi bi-hand-thumbs-down"></i>
			{% endif %}
			  </a>
			  {{ answer.dislikes.count }}
			  {% if not is_user_logged_in %}
				<small><a href="{% url 'login' %}?next={% firstof request.path '/' %}">Login</a> to like</small>
			 {% endif %}
        </div>
		</div>
		</div>
	 </div>
	</div>
{% endfor %}
 </article>

home/templates/home/explore.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'home/CSS/explore-page.css' %}">
<body class="main-bg">

<form method="GET" class="container">
<div class="m-3" >

    <div class="row my-4">
        <div class="col-2">
            <a href="{% url 'new-question' %}" class="btn shlifim-btn" role="button">Ask new question</a>
        </div>

    </div>

    {% if tag != None %}
    <div class="tags-msg p-3">
        <p><b>Showing all questions that include the tag: #{{ tag }}</b></p>
        <a href="{% url 'explore-page' %}"><small>Show me all questions</small></a>
    </div>

    {% endif %}

	{% for question in questions %}
	<div class=" question-display p-2 row m-0 border">
	    <img class="subject-img" src="{% get_static_prefix %}home\subjects-images\{{question.subject|lower}}.png">
            <div class="col-3">
                <a style="color:#6FB5EE" href="{% url 'question-detail' question.id %}"><b>{{ question.title }}</b></a>
            </div>
            <div class="col-3">
                <div class="row">
                    <span>{{ question.subject }}
					{% if question.sub_subject != None %}
					, {{ question.sub_subject }}
					{% endif %} </span>
                </div>
                <div class="row mt-2">
                        <div >
                            {% for tag in question.tag_set.all %}
                                <span class="badge badge-pill badge-secondary">
								 <a href="{% url 'explore-page' %}?tag={{ tag }}" class="nostyle">
								#{{tag.tag_name}}</a></span>
                            {% endfor %}
                        </div>
                </div>
            </div>
            <div class=" col">
                <p>{{question.get_grade_display }} </p>
            </div>
            <div class="col">
                <span >
                    {{question.get_answers_num}} answers
                </span>
            </div>
            <div class="col">
                	<b>by <a href="{% url 'user-page' question.profile.pk  %}">{{ question.profile }}</a></b>
					<br/>
                <small class="text-muted date">{{ question.publish_date|date:"d F, Y" }}</small>
            </div>
	 </div>

    {% empty %}
            <div class=" row font-weight-bold text-center">
                <span>No questions were found</span>
            </div>
	{% endfor %}

    </div>
</div>
</form>

</body>
{% endblock content %}

home/templates/home/landingpage.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}


<link rel="stylesheet" type="text/css" href="{% static 'home/landing-page.css' %}">
<body class="landing-bg">
    <div class="center">
         <img src="{% static 'home/animated-logo.gif' %}" alt="Shlifim Logo gif" class="row rounded mx-auto d-block my-5" >
        <div  class=" text-center">
            <h1 class="text-center font-weight-bold txt">Your place to Ask, Answer & Discover</h1>
                <a href="{% url 'explore-page' %}" type="button" class="btn m-4 get_started_btn rounded-pill active" aria-pressed="true">Get Started</a>
        </div>

    </div>
</body>
{% endblock content %}

home/templates/home/login.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'home/CSS/login_style.css' %}">
<html>
  <body class ="main-bg">
    <br><br>
    <div class="content">
    <h1>Login</h1>
    <br><br>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br><br>
        <button type="submit" class="login-btn">Login</button>
      </form>
    </div>
  </body>
   
</html>
{% endblock %}

home/templates/home/question_detail.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'home/CSS/display_question_style.css' %}">
<body class ="main-bg">
 <main role="main" class="container">
<div class="row">
<div class="col-md-12">
  <div class="question-container col-md-10">
	<div class="question-display">
	  <div class="question-title">
		<img class="rounded-circle question-img" 
		src="{% get_static_prefix %}home\subjects-images\{{question.subject|lower}}.png">
		<h3> {{ question.title }} </h3>
		{% if question.profile.user == user %}
		<form method="POST" action="{% url 'question-delete' question.pk %}" class="delete">
		{% csrf_token %}
		<input type="submit" class="delete right" value="Delete" onclick="return confirm('Are you sure?');">
		</form>
		{% endif %}
	  </div>
	  <div class="question-metadata">
		<small class="text-muted date">{{ question.publish_date|date:"F d, Y" }}</small>
		{% if question.is_edited %}
			<small class="text-muted date ml-3"><span>*edited*</span></small>
			{% endif %}
		<b>by <a href="{% url 'user-page' question.profile.pk  %}">{{ question.profile }}</a> </b>
	  </div>
		<div class="question-body">
		  <p class="question-content">{{ question.content | safe }}</p>
		</div>
		 <div class="pt-2">
				{% for tag in question.tag_set.all %}
				   <span class="badge badge-pill badge-secondary">
							 <a href="{% url 'explore-page' %}?tag={{ tag }}" class="nostyle">
							#{{tag.tag_name}}</a></span>
				{% endfor %}
          </div>
	</div>
 </div>
 <div class="col-md-8" id="answers">
	  <a class="ans-counter"><b>{{ answersCount }} Answer{{ answersCount|pluralize:",s" }} </b></a>
	<small class="ml-4"> Order answers by:<br></small>
	<form class="d-flex">
		<a href="{% url 'question-detail' question.pk  %}?sortanswersby=date&page#answers" class="ml-4 btn btn-primary">Publish Date</a>
		<a href="{% url 'question-detail' question.pk  %}?sortanswersby=votes&page#answers" name="q" class="ml-4 btn btn-primary" value="votes">Votes Count</a>	
	</form>
 </div>
 <!-- Answers Part -->
 {% include 'home/answers_display.html' %}
 </div>
 </div>  
 </main>
  </body>

<footer class="container">
	{% if request.user.is_authenticated %}
	<div class="add-comment">
	  <form method="POST" action="." class="commenting-form">
		{% csrf_token %}
		<div class="col-md-12">
		  <div id="comment-form">
			{{ form }}
			{{ form.media }}
		  </div>
		  <div >
			<button type="submit" class="btn btn-secondary">Submit Comment</button>
		  </div>
		</div>
	  </form>
	</div>
	{% else %}
	<a href="{% url 'login' %}?next={% firstof request.path '/' %}" id="not-authenticated" class="btn btn-primary">Login to comment</a>
	{% endif %}
  </div>
</footer>

{% endblock content %}

home/templates/home/tags.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'home/CSS/tags_style.css' %}">
<html>
    <body>
        <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
            <br><br>
            <center><h1>Tags</h1></center>
            <br><br>
            <div class="tags-grid">
                <form class="d-flex">
                    <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-light" type="submit" ng-click="ctrl.clearSearch()">Search</button>
                </form>
                <br><br>
                <div class="wrapper">
                    {% for tag in tags %}

                      <div class="card border-secondary mb-3">
                            <div class="card-body">
                                <p class="card-text tag-text">
                                    <a href="{% url 'explore-page' %}?tag={{ tag }}">#{{ tag.tag_name }}</a>
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            </div>
        </div>
		</main>
    </body>
</html>
{% endblock content %}

home/templates/home/user_page.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'home/CSS/user_page.css' %}">
<body class="main-bg">
<main role="main" class="container">
 <h1 class="title">{{  profile.user.username }} Profile page</h1>
 <p> Date joined: {{ profile.user.date_joined | date:"Y-F-d" }}</p>
 <p> Gender: {{ profile.gender }}</p>
 <p> Number of Questions: {{ user_questions.count }}</p>
 <p> Number of Answers: {{ user_answers.count }}</p>
<div class="row">
  <div class="column left-col border border-dark" >
   <h2>User Questions</h2>
   {% for question in user_questions %}
		<a class="questions" href="{% url 'question-detail' question.pk  %}">{{question}}</a>
		<br/>
	{% endfor %}
  </div>
  <div class="column right-col border border-dark">
  <h2>User Answers</h2>
  {% for answer in user_answers %}
		<a class="answers" href="{% url 'question-detail' answer.question.pk  %}">Answered {{answer.question}}</a>
		<br/>
	{% endfor %}
  </div>
</div>
</main>
</body>
{% endblock content %}